remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Gabe Busto
tagline: a place where i document my work, thoughts, and experiments
description: a place where i document my work, thoughts, and experiments
